### ISSUE TITLE
Button won't fit

### ISSUE THREAD

**Issue by jerone** [skratchdot/github-repo-counts.user.js#1]
Still useful script!

The search button won't fit anymore: 
![github-repo-counts](https://cloud.githubusercontent.com/assets/55841/9043843/ca3293ea-3a18-11e5-807e-cab3c04cd4cf.png)

I would have send a PR were it not that all scripts logic is in the gists.

**Comment by skratchdot** [comment]
Oops. It's been a long time since I've updated any of these Github scripts. I've been meaning to spend a bit of time to update all of them.  Thanks for logging this.

**Comment by jerone** [comment]
Yeah seems to be 2 years now. Some still work and are very useful. I've built a few UserScripts for GitHub myself too; https://github.com/jerone/UserScripts/blob/master/README.md#github
